blank_issues_enabled: false  # Desativa a criação de issues em branco

contact_links:
  - name: ❓ Perguntas e Suporte
    url: https://github.com/usuario/repositorio/discussions
    about: Use o fórum de discussões para dúvidas gerais e suporte.

issue_templates:
  - name: 🐛 Bug Report
    path: bug_report.md
    about: Relate um problema encontrado no sistema.
    labels: [bug]

  - name: 🚀 Feature Request
    path: feature_request.md
    about: Sugira uma nova funcionalidade ou melhoria.
    labels: [enhancement]
